CREATE OR REPLACE TABLE "UNITY_DEV_DB"."PUBLIC"."TEST_DEV" 
(   "DEV_C1" STRING, 
    "DEV_C2" STRING
);

INSERT INTO "UNITY_DEV_DB"."PUBLIC"."TEST_DEV" 
(DEV_C1, DEV_C2)
VALUES
('YASH_DEV_UPDATED', 'UPDATED_DEV_YASH');