CREATE OR REPLACE TABLE "UNITY_PROD_DB"."PUBLIC"."TEST_PROD" 
(   "PROD_C1" STRING, 
    "PROD_C2" STRING
);

INSERT INTO "UNITY_PROD_DB"."PUBLIC"."TEST_PROD" 
(PROD_C1, PROD_C2)
VALUES
('YASH_PROD', 'PROD_YASH');
