CREATE OR REPLACE TABLE UNITY_{{ env }}_DB.PUBLIC.TEST_MIGRATION
(   "C1" STRING, 
    "C2" STRING
);

INSERT INTO UNITY_{{ env }}_DB.PUBLIC.TEST_MIGRATION
(DEV_C1, DEV_C2)
VALUES
('YASH_DEV', 'DEV_YASH');